apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: your-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: 'https://github.com/your-username/your-repo.git'
    path: '/path/to/your/kubernetes/manifests'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
