# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-interview-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: devops-interview
  template:
    metadata:
      name: devops-interview
      labels:
        app: devops-interview
    spec:
      containers:
      - name: devops-interview
        image: emmylong1/devops-interview:v1
        ports:
        - containerPort: 8000
