apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-interview-app-deployment
  labels:
    app: devops-interview-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-interview-app
  template:
    metadata:
      labels:
        app: devops-interview-app
    spec:
      containers:
      - name: devops-interview-app
        image: nginx:latest
        ports:
        - containerPort: 80
