# Service
apiVersion: v1
kind: Service
metadata:
  name: devops-interview-service
spec:
  selector:
    app: devops-interview
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort: 30001
