# Service
apiVersion: v1
kind: Service
metadata:
  name: devops-interview-service
spec:
  selector:
    app: devops-interview
  ports:
   - port: 80
     targetPort: 8000
     nodePort: 30001
     protocol: TCP
  type: NodePort

