# Cluster IP  Service
apiVersion: v1
kind: Service
metadata:  
  name: devops-interview
spec:
  selector:    
    app: devops-interview
  type: LoadBalancer
  ports:  
   - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000
    
    


