apiVersion: v1
kind: Service
metadata:
  name: devops-interview-app
  labels:
    app: devops-interview-app
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 80
    nodePort: 30002
    protocol: TCP
    name: http
  selector:
    app: devops-interview-app
