# Cluster IP  Service
apiVersion: v1
kind: Service
metadata:  
  name: devops-interview
spec:
  selector:    
    app: devops-interview
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
