apiVersion: v1
kind: Service
metadata:
  name: devops-interview-app
  labels:
    app: devops-interview-app
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: devops-interview-app
