apiVersion: v1
kind: Service
metadata:
  name: devops-interview-app
  labels:
    run: devops-interview-app
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: devops-interview-app
